name: Notify Webhook on Any Script File Change

on:
  push:
    paths:
      - "func_Get-Emoji.ps1"  # Watch this file, you can add more later :)
      - "README.md" # prefer this for testing ;-)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # Needed to get file changes

      - name: Get Changed Files as JSON Array
        id: changed_files
        run: |
          # Get the list of files changed in the current commit
          FILES=$(git diff --name-only ${{ github.sha }}^..${{ github.sha }})

          # Convert the file list to a JSON array using jq
          CHANGED_JSON=$(echo "$FILES" | jq -R -s -c 'split("\n")[:-1]')
          echo "changed_files=$CHANGED_JSON" >> $GITHUB_ENV

      - name: Send Webhook with JSON Payload
        run: |
          curl -X POST https://webhook.site/aa362e00-e471-4188-8ba5-e1cb93dd3a9e \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
          -d '{
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "changed_files": ${{ env.changed_files }}
          }'
