name: Notify Webhook on Any Script File Change

on:
  push:  # Triggers on any commit pushed to the repo
    paths: 
      - "func_Get-Emoji.ps1"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        run: |
          curl -X POST https://webhook.site/aa362e00-e471-4188-8ba5-e1cb93dd3a9e \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.MY_WEBHOOK_TOKEN }}" \
          -d '{"repository": "${{ github.repository }}", "commit": "${{ github.sha }}"}'

